config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, :text, presence: true
  validates :user_id, uniqueness: { scope: :track_id }

  belongs_to(
    :user,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  belongs_to(
    :track,
    :class_name => "Track",
    :foreign_key => :track_id,
    :primary_key => :id
  )
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :can_destroy, only: [:destroy]

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.track_id = params[:track_id]
    @track = @note.track
    if @note.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to track_url(@track)
      #fail
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @note = Note.find(params[:id])
    @track = Track.find(@note.track_id)
    if @note.destroy
      redirect_to track_url(@track)
    else
      redirect_to track_url(@track)
    end
  end

  def note_params
    params.require(:note).permit(:track_id, :user_id, :text)
  end

  def can_destroy
    @note = Note.find(params[:id])
    render text: "Can't do that!" unless current_user.id == @note.user_id
  end
end

app/views/notes/_form.html.erb
<h2>New Note:</h2>

<form action="<%= track_notes_url(@track) %>" method="post">
  <%= auth_token %>
  <textarea name="note[text]"></textarea>

  <br>
  <button>Submit</button>
</form>

app/views/notes/_note.html.erb
<h2>Notes:</h2>
<table>
  <th align="left">Note</th>
  <th align="left">Author</th>
  <% @notes.each do |note| %>
    <tr>
      <td><%= note.text %></td>
      <td><%= note.user.email %></td>
      <% if current_user == note.user %>
        <td><%= button_to "Delete", track_note_url(@track, note), :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>