config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :album_id, :title, :track_number, :track_type, presence: true

  belongs_to(
    :album,
    :class_name => "Album",
    :foreign_key => :album_id,
    :primary_key => :id
  )

  has_many(
    :notes,
    :class_name => "Note",
    :foreign_key => :track_id,
    :primary_key => :id
  )
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :check_signin

  def new
    @track = Track.new
    @albums = Album.find(params[:album_id]).band.albums
    @album = Album.find(params[:album_id])
    @band = @album.band
    render :new
  end

  def create
    @track = Track.new(track_params)
    @album = Album.find(@track.album_id)
    if @track.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to new_album_track_url(@album)
    end
  end

  def update
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    if @track.update(track_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to edit_track_url
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    if @track.destroy
      redirect_to album_url(@album)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to album_url(@album)
    end
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @band = @album.band
    @notes = Note.includes(:user).where(track_id: @track.id)
    @note = Note.new
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
    @album = @track.album
    @band = @album.band
    render :edit
  end

  def track_params
    params.require(:track).permit(:title, :album_id, :track_number, :track_type, :lyrics)
  end

end

app/views/tracks/edit.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > <a href="<%= album_url(@album) %>"><a href="<%= album_url(@album) %>"><%= @album.title %></a> > <a href="<%= track_url(@track) %>"><%= @track.title %></a> > Edit</h3>

<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>

  <label>
    Track Title
    <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>
  <br>

  <label>
    Album
    <select name="track[album_id]">
      <% @albums.each do |album| %>
        <option
          value="<%= album.id %>"
          <%= "selected" if params[:album_id].to_i == album.id %>>
          <%= album.title %>
        </option>
      <% end %>
    </select>
  </label>
  <br>

  <label>
    Track Number
      <input type="number" name="track[track_number]" value="<%= @track.track_number %>">
  </label>
  <br>

  <label>
    Track Type
    <br>
    <label>
      Regular
      <input type="radio" name="track[track_type]" value="Regular">
    </label>

    <label>
      Bonus
      <input type="radio" name="track[track_type]" value="Bonus">
    </label>
  </label>
  <br>

  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
  </label>
  <br>

  <button>Edit Track</button>
</form>

app/views/tracks/new.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > <a href="<%= album_url(@album) %>"><%= @album.title %></a> > Add Track</h3>

<form action="<%= tracks_url %>" method="post">
  <%= auth_token %>

  <label>
    Track Title
    <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>
  <br>

  <label>
    Album
    <select name="track[album_id]">
      <% @albums.each do |album| %>
        <option
          value="<%= album.id %>"
          <%= "selected" if params[:album_id].to_i == album.id %>>
          <%= album.title %>
        </option>
      <% end %>
    </select>
  </label>
  <br>

  <label>
    Track Number
      <input type="number" name="track[track_number]" value="<%= @track.track_number %>">
  </label>
  <br>

  <label>
    Track Type
    <br>
    <label>
      Regular
      <input type="radio" name="track[track_type]" value="Regular">
    </label>

    <label>
      Bonus
      <input type="radio" name="track[track_type]" value="Bonus">
    </label>
  </label>
  <br>

  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
  </label>
  <br>

  <button>Add Track</button>
</form>

app/views/tracks/show.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > <a href="<%= album_url(@album) %>"><%= @album.title %></a> > <%= @track.title %></h3>


<h2>Lyrics:</h2>
<%= ugly_lyrics(@track.lyrics) %>

<%= render partial: "notes/note" %>
<%= render partial: "notes/form" %>