config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  RECORDING_TYPES = %w(Live Studio)
  validates :title, :band_id, :recording_type, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :band,
    :class_name => "Band",
    :foreign_key => :band_id,
    :primary_key => :id
  )

  has_many(
    :tracks,
    :dependent => :destroy,
    :class_name => "Track",
    :foreign_key => :album_id,
    :primary_key => :id
  )
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_signin

  def new
    @album = Album.new
    @band = Band.find(params[:band_id])
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    @band = @album.band
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      @bands = Band.all
      render :new
    end
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to band_url(@album.band)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      redirect_to bands_url
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to bands_url
    end
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
    @tracks = @album.tracks.order(:track_number)
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    @band = @album.band
    render :edit
  end

  def album_params
    params.require(:album).permit(:title, :recording_type, :band_id)
  end
end

app/views/albums/edit.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > <a href="<%= album_url(@album) %>"><%= @album.title %></a> > Edit</h3>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>
    Album Title
    <input type="text" name="album[title]" value="<%= @album.title %>">
  </label>
  <br>

  <label>
    Recording Type:
    <br>
    <% Album::RECORDING_TYPES.each do |rec_type| %>
      <label>
        <%= rec_type %>
        <input type="radio"
        name="album[recording_type]"
        value="<%= rec_type %>"
        <%= "checked" if @album.recording_type == rec_type %>>
      </label>
    <% end %>
  </label>
  <br>

  <button>Edit Album</button>
</form>

app/views/albums/new.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > Add</h3>


<form action="<%= albums_url %>" method="post">
  <%= auth_token %>

  <label>
    Album Title
    <input type="text" name="album[title]" value="<%= @album.title %>">
  </label>
  <br>

  <label>
    <select name="album[band_id]">
      <% @bands.each do |band| %>
        <option
          value="<%= band.id %>"
          <%= "selected" if params[:band_id].to_i == band.id %>><%= band.name %></option>
      <% end %>
    </select>
  </label>
  <br>

  <label>
    Recording Type:
    <br>
    <% Album::RECORDING_TYPES.each do |rec_type| %>
      <label>
        <%= rec_type %>
        <input type="radio"
        name="album[recording_type]"
        value="<%= rec_type %>"
        <%= "selected" if @album.recording_type == rec_type %>>
      </label>
    <% end %>
  </label>
  <br>

  <button>Add Album</button>
</form>

app/views/albums/show.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <a href="<%= band_url(@band) %>"><%= @band.name %></a> > <%= @album.title %></h3>


<table>
  <th align="left">Num</th>
  <th align="left">Title</th>
  <% @tracks.each do |track| %>
    <tr>
      <td><%= track.track_number %></td>
      <td><a href="<%= track_url(track) %>"><%= track.title %></a>
      <td><%= button_to "Edit", edit_track_url(track), :method => :get %></td>
      <td><%= button_to "Delete", track_url(track), :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br>
<a href="<%= new_album_track_url(@album) %>">Add New Track</a>