config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :update, :destroy, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:create, :update, :destroy]
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many(
    :albums,
    :dependent => :destroy,
    :class_name => "Album",
    :foreign_key => :band_id,
    :primary_key => :id
  )

  has_many(
    :tracks,
    :dependent => :destroy,
    :through => :albums,
    :source => :tracks
  )
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :check_signin

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end

  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_band_url(@band)
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    render :show
  end

  def index
    @bands = Band.all
    render :index
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/views/bands/_form.html.erb
<% @header = @band.persisted? ? "Edit Band" : "New Band" %>
<% @action = @band.persisted? ? band_url(@band) : bands_url %>
<% @method = @band.persisted? ? "put" : "post" %>
<% @button_label = @band.persisted? ? "Edit Band" : "Create Band" %>

<h3><a href="<%= bands_url %>">All Bands</a>
  <% if @band.persisted? %>
    > <a href="<%= @action %>"><%= @band.name  %></a>
  <% end %>
  > <%= @header %></h3>

<form action="<%= @action %>" method="post">
 <input type="hidden" name="_method" value="<%= @method %>">
 <%= auth_token %>

 <label>
   Band Name
   <input type="text" name="band[name]" value="<%= @band.name %>">
 </label>
 <br>

 <button><%= @button_label %></button>
</form>

app/views/bands/edit.html.erb
<%= render partial: "form" %>

app/views/bands/index.html.erb
<h3>All Bands</h3>
<table>
  <% @bands.each do |band| %>
  <tr>
    <td><a href="<%= band_url(band) %>"><%= band.name %></a></td>
    <td><%= button_to "Edit", edit_band_url(band), :method => :get %><td>
    <td><%= button_to "Delete", band_url(band), :method => :delete %><td>
  </tr>
  <% end %>
</table>
<br>

<a href="<%= new_band_url %>">Add Band</a>

app/views/bands/new.html.erb
<%= render partial: "form" %>

app/views/bands/show.html.erb
<h3><a href="<%= bands_url %>">All Bands</a> > <%= @band.name %></h3>

<table>
  <th align="left">Title</th>
  <th align="left">Recording Type</th>
  <% @albums.each do |album| %>
  <tr>
    <td><a href="<%= album_url(album) %>"><%= album.title %></a></td>
    <td><%= album.recording_type %></td>
    <td><%= button_to "Edit", edit_album_url(album), :method => :get %><td>
    <td><%= button_to "Delete", album_url(album), :method => :delete %><td>
  </tr>
  <% end %>
</table>
<br>

<a href="<%= new_band_album_url(@band) %>">Add New Album</a>